// <auto-generated />
#pragma warning disable 1591
#region T4Decorator

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace T4Decorators.Host.Decorators
{
    [GeneratedCode("T4Decorator", "1.0"), DebuggerNonUserCode]
    internal partial class SimpleStaticTestDecorator
    {
        public string GetterTest
        {
            get { return SimpleStaticTestDecorator.SimpleTest.GetterTest; }
        }

        public string SetterTest
        {
            set { SimpleStaticTestDecorator.SimpleTest.SetterTest = value; }
        }

        public string GetterAndSetterTest
        {
            get { return SimpleStaticTestDecorator.SimpleTest.GetterAndSetterTest; }
            set { SimpleStaticTestDecorator.SimpleTest.GetterAndSetterTest = value; }
        }

        public void VoidMethodTest()
        {
            SimpleStaticTestDecorator.SimpleTest.VoidMethodTest();
        }

        public T4Decorators.Host.Generated.Interfaces.ISimpleTest GetMethodTest()
        {
            return SimpleStaticTestDecorator.SimpleTest.GetMethodTest();
        }

        public void SetTestMethod(T4Decorators.Host.Generated.Interfaces.ISimpleTest simpleTest)
        {
            SimpleStaticTestDecorator.SimpleTest.SetTestMethod(simpleTest);
        }

        public T4Decorators.Host.Generated.Interfaces.ISimpleTest OutMethodTest(out T4Decorators.Host.Generated.Interfaces.ISimpleTest simpleTest)
        {
            return SimpleStaticTestDecorator.SimpleTest.OutMethodTest(out simpleTest);
        }

        public T4Decorators.Host.Generated.Interfaces.ISimpleTest RefMethodTest(ref T4Decorators.Host.Generated.Interfaces.ISimpleTest simpleTest)
        {
            return SimpleStaticTestDecorator.SimpleTest.RefMethodTest(ref simpleTest);
        }

    }
}
#endregion T4Decorator
#pragma warning restore 1591
