// <auto-generated />
#pragma warning disable 1591
#region T4Decorator

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace T4Decorators.Host.Decorators
{
    [GeneratedCode("T4Decorator", "1.0"), DebuggerNonUserCode]
    internal partial class SimpleConstructorOnlyTestDecorator
    {
        public string GetterTest
        {
            get { return this.simpleTest.GetterTest; }
        }

        public string SetterTest
        {
            set { this.simpleTest.SetterTest = value; }
        }

        public string GetterAndSetterTest
        {
            get { return this.simpleTest.GetterAndSetterTest; }
            set { this.simpleTest.GetterAndSetterTest = value; }
        }

        public void VoidMethodTest()
        {
            this.simpleTest.VoidMethodTest();
        }

        public T4Decorators.Host.Generated.Interfaces.ISimpleTest GetMethodTest()
        {
            return this.simpleTest.GetMethodTest();
        }

        public void SetTestMethod(T4Decorators.Host.Generated.Interfaces.ISimpleTest simpleTest)
        {
            this.simpleTest.SetTestMethod(simpleTest);
        }

        public T4Decorators.Host.Generated.Interfaces.ISimpleTest OutMethodTest(out T4Decorators.Host.Generated.Interfaces.ISimpleTest simpleTest)
        {
            return this.simpleTest.OutMethodTest(out simpleTest);
        }

        public T4Decorators.Host.Generated.Interfaces.ISimpleTest RefMethodTest(ref T4Decorators.Host.Generated.Interfaces.ISimpleTest simpleTest)
        {
            return this.simpleTest.RefMethodTest(ref simpleTest);
        }

    }
}
#endregion T4Decorator
#pragma warning restore 1591
