// <auto-generated />
#pragma warning disable 1591
#region T4Decorator

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace T4Decorators.Host.Decorators
{
    [GeneratedCode("T4Decorator", "1.0"), DebuggerNonUserCode]
    internal partial class SimpleStaticDecorator
    {
        public string Read
        {
            get { return SimpleStaticDecorator.simple.Read; }
        }

        public string Write
        {
            set { SimpleStaticDecorator.simple.Write = value; }
        }

        public string ReadWrite
        {
            get { return SimpleStaticDecorator.simple.ReadWrite; }
            set { SimpleStaticDecorator.simple.ReadWrite = value; }
        }

        public void VoidMethod()
        {
            SimpleStaticDecorator.simple.VoidMethod();
        }

        public T4Decorators.Host.Generated.Interfaces.ISimple GetMethodTest()
        {
            return SimpleStaticDecorator.simple.GetMethodTest();
        }

        public void OneParamMethod(T4Decorators.Host.Generated.Interfaces.ISimple simple)
        {
            SimpleStaticDecorator.simple.OneParamMethod(simple);
        }

        public T4Decorators.Host.Generated.Interfaces.ISimple OutParamMethod(out T4Decorators.Host.Generated.Interfaces.ISimple simple)
        {
            return SimpleStaticDecorator.simple.OutParamMethod(out simple);
        }

        public T4Decorators.Host.Generated.Interfaces.ISimple RefParamMethod(ref T4Decorators.Host.Generated.Interfaces.ISimple simple)
        {
            return SimpleStaticDecorator.simple.RefParamMethod(ref simple);
        }

    }
}
#endregion T4Decorator
#pragma warning restore 1591
