// <auto-generated />
#pragma warning disable 1591
#region T4Decorator

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;




namespace T4Decorators.Host.Generated
{
    internal interface ITracingContextFactory
    {
        IDisposable CreateTracingContext(string name);
    }
}

#endregion T4Decorator
#pragma warning restore 1591

