// <auto-generated />
#pragma warning disable 1591
#region T4Decorator

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace T4Decorators.Host.Decorators
{
    [GeneratedCode("T4Decorator", "1.0"), DebuggerNonUserCode]
    internal partial class DerivedTestDecorator
    {
        public string GetterTest
        {
            get { return this.derivedInterface.GetterTest; }
        }

        public string SetterTest
        {
            set { this.derivedInterface.SetterTest = value; }
        }

        public string GetterAndSetterTest
        {
            get { return this.derivedInterface.GetterAndSetterTest; }
            set { this.derivedInterface.GetterAndSetterTest = value; }
        }

        public void VoidMethodTest()
        {
            this.derivedInterface.VoidMethodTest();
        }

        public T4Decorators.Host.Generated.Interfaces.ISimpleTest GetMethodTest()
        {
            return this.derivedInterface.GetMethodTest();
        }

        public void SetTestMethod(T4Decorators.Host.Generated.Interfaces.ISimpleTest simpleTest)
        {
            this.derivedInterface.SetTestMethod(simpleTest);
        }

        public T4Decorators.Host.Generated.Interfaces.ISimpleTest OutMethodTest(out T4Decorators.Host.Generated.Interfaces.ISimpleTest simpleTest)
        {
            return this.derivedInterface.OutMethodTest(out simpleTest);
        }

        public T4Decorators.Host.Generated.Interfaces.ISimpleTest RefMethodTest(ref T4Decorators.Host.Generated.Interfaces.ISimpleTest simpleTest)
        {
            return this.derivedInterface.RefMethodTest(ref simpleTest);
        }

        public T4Decorators.Host.Generated.Interfaces.ISimpleTest GetTestDefault(T4Decorators.Host.Interfaces.IDerivedInterface derivedInterface, bool defaultBool)
        {
            return this.derivedInterface.GetTestDefault(derivedInterface, defaultBool);
        }

        public T4Decorators.Host.Interfaces.IDerivedInterface MethodWithParamsTest(params string[] testParams)
        {
            return this.derivedInterface.MethodWithParamsTest(testParams);
        }

    }
}
#endregion T4Decorator
#pragma warning restore 1591
