// <auto-generated />
#pragma warning disable 1591
#region T4Decorator

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace T4Decorators.Host.Decorators
{
    [GeneratedCode("T4Decorator", "1.0"), DebuggerNonUserCode]
    internal partial class DerivedTracingDecorator : T4Decorators.Host.Generated.ITracingContextFactory
    {

        public string Read
        {
            get
            {
                using (this.CreateTracingContext("T4Decorators.Host.Interfaces.IDerivedInterface.Read(Getter)"))
                {
                    return this.derivedInterface.Read;
                }
            }
        }

        public string Write
        {
            set
            {
                using (this.CreateTracingContext("T4Decorators.Host.Interfaces.IDerivedInterface.Write(Setter)"))
                {
                    this.derivedInterface.Write = value;
                }
            }
        }

        public string ReadWrite
        {
            get
            {
                using (this.CreateTracingContext("T4Decorators.Host.Interfaces.IDerivedInterface.ReadWrite(Getter)"))
                {
                    return this.derivedInterface.ReadWrite;
                }
            }
            set
            {
                using (this.CreateTracingContext("T4Decorators.Host.Interfaces.IDerivedInterface.ReadWrite(Setter)"))
                {
                    this.derivedInterface.ReadWrite = value;
                }
            }
        }

        public void VoidMethod()
        {
            using (this.CreateTracingContext("T4Decorators.Host.Interfaces.IDerivedInterface.VoidMethod()"))
            {
                this.derivedInterface.VoidMethod();
            }
        }

        public T4Decorators.Host.Generated.Interfaces.ISimple GetMethodTest()
        {
            using (this.CreateTracingContext("T4Decorators.Host.Interfaces.IDerivedInterface.GetMethodTest()"))
            {
                return this.derivedInterface.GetMethodTest();
            }
        }

        public void OneParamMethod(T4Decorators.Host.Generated.Interfaces.ISimple simple)
        {
            using (this.CreateTracingContext("T4Decorators.Host.Interfaces.IDerivedInterface.OneParamMethod(simple)"))
            {
                this.derivedInterface.OneParamMethod(simple);
            }
        }

        public T4Decorators.Host.Generated.Interfaces.ISimple OutParamMethod(out T4Decorators.Host.Generated.Interfaces.ISimple simple)
        {
            using (this.CreateTracingContext("T4Decorators.Host.Interfaces.IDerivedInterface.OutParamMethod(out simple)"))
            {
                return this.derivedInterface.OutParamMethod(out simple);
            }
        }

        public T4Decorators.Host.Generated.Interfaces.ISimple RefParamMethod(ref T4Decorators.Host.Generated.Interfaces.ISimple simple)
        {
            using (this.CreateTracingContext("T4Decorators.Host.Interfaces.IDerivedInterface.RefParamMethod(ref simple)"))
            {
                return this.derivedInterface.RefParamMethod(ref simple);
            }
        }

        public T4Decorators.Host.Generated.Interfaces.ISimple DefaultParamMethod(T4Decorators.Host.Interfaces.IDerivedInterface derivedInterface, bool defaultBool)
        {
            using (this.CreateTracingContext("T4Decorators.Host.Interfaces.IDerivedInterface.DefaultParamMethod(derivedInterface, defaultBool)"))
            {
                return this.derivedInterface.DefaultParamMethod(derivedInterface, defaultBool);
            }
        }

        public T4Decorators.Host.Interfaces.IDerivedInterface ParamsParamMethod(params string[] testParams)
        {
            using (this.CreateTracingContext("T4Decorators.Host.Interfaces.IDerivedInterface.ParamsParamMethod(testParams)"))
            {
                return this.derivedInterface.ParamsParamMethod(testParams);
            }
        }

    }
}
#endregion T4Decorator
#pragma warning restore 1591
